version: '3.4'

networks:
  sunucutest:
services:
  basedb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=test@12345#
    networks:
      - sunucutest
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/sunucuTest/WebAPI/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - basedb
    networks:
      - sunucutest
